- hosts: server
  become: true
  tasks:

  - name: "update & upgrade system"
    apt:
      update_cache: yes
      upgrade: dist

  - name: "install prerequisite"
    apt:
      update_cache: yes
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

  - name: "add GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: "set up repository"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: "update system"
    apt:
      update_cache: yes
  - name: "Install Docker Engine, containerd, and Docker Compose"
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

  - name: add user permissions
    shell: "sudo usermod -aG docker {{ user }}"

  - name: Install python3
    apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: true
    tags:
      - general-packages
      - tree

  - name: install docker pip package
    pip:
      name:
        - docker
        - docker-compose
      state: present

  # - name: Creates directory
  #   file:
  #     path: /home/{{ user }}/{{ directory }}
  #     state: directory
  #     owner: "{{ user }}"
  #     group: "{{ user }}"
  #     mode: 0775
  #     recurse: yes
  #   tags:
  #     - install-thedudebridge

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/ilhaskam/Downloads/thedudebridge
      dest: /home/{{ user }}
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  # - name: "Copy file"
  #   copy:
  #     src: "{{ item }}"
  #     dest: /home/{{ user }}
  #     owner: "{{ user }}"
  #     group: "{{ user }}"
  #     mode: 0755
  #   with_items:
  #     - ../thedudebridge
  #   tags:
  #     - install-thedudebridge

  - name: Build Image
    docker_image:
      name: ilhaskam/thedudebridge:v1
      build:
        path: /home/{{ user }}/{{ directory }}
        pull: no
      source: build
  
  - name: docker-compose up -d
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/{{ user }}/{{ directory }}

  vars:
    user: "ubuntu"
    directory: thedudebridge





